export const WORDS = [
  "airplane",
  "alien",
  "apple",
  "astronaut",
  "banana peel",
  "beach ball",
  "beehive",
  "bicycle",
  "birthday cake",
  "blender",
  "backpack",
  "boomerang",
  "bowling",
  "bubble bath",
  "burrito",
  "cactus",
  "camera",
  "campfire",
  "castle",
  "cheeseburger",
  "chef hat",
  "chocolate bar",
  "circus tent",
  "coffee",
  "crab",
  "crown",
  "detective",
  "dinosaur",
  "disco ball",
  "donut",
  "dragon",
  "drum set",
  "fairy",
  "ferris wheel",
  "fire truck",
  "fireworks",
  "flamingo",
  "flying saucer",
  "football helmet",
  "ghost",
  "giant robot",
  "giraffe",
  "globe",
  "guitar",
  "hammock",
  "haunted house",
  "helicopter",
  "hot air balloon",
  "ice cream cone",
  "island",
  "jacket",
  "jellyfish",
  "kangaroo",
  "kayak",
  "kite",
  "koala",
  "laser sword",
  "lighthouse",
  "llama",
  "magic wand",
  "mermaid",
  "microscope",
  "monster",
  "moon",
  "mummy",
  "nachos",
  "ninja",
  "octopus",
  "pancakes",
  "parrot",
  "penguin",
  "pirate ship",
  "pizza",
  "popcorn",
  "popsicle",
  "rainbow",
  "robot dinosaur",
  "roller coaster",
  "sandcastle",
  "scarecrow",
  "skateboard",
  "snowman",
  "space rocket",
  "spaghetti",
  "squirrel",
  "submarine",
  "sunglasses",
  "surfboard",
  "taco",
  "teapot",
  "telescope",
  "toothbrush",
  "treasure chest",
  "umbrella",
  "unicorn",
  "volcano",
  "waffle",
  "waterfall",
  "wizard",
  "zombie"
];

export function pickWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)] ?? "apple";
}
